# ===============================
# SERVER CONFIG
# ===============================
server.port: 8080
# ===============================
# SPRING (DATABASE / H2 / JPA / HIBERNATE / THYMELEAF)
# ===============================
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:./src/main/resources/h2/ksr-one
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html
#    resources:
#      static-locations: classpath:/static/
#      cache-period: 0
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
#  profiles.active: secure
# ===============================
# MANAGEMENT (ekspozycja endpointów - all * only for dev)
# Website: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
# Paragraph 2.2 => production-ready-endpoints-exposing-endpoints
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'